// <auto-generated />
namespace EventHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addtablesforfollowingevents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtablesforfollowingevents));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191457481_Add tables for following events."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
