// <auto-generated />
namespace EventHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEventIdtoEventstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEventIdtoEventstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201612212234250_Add EventId to Events table."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
